# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

image: docker:latest
services:
  - docker:dind


stages:          # List of stages for jobs, and their order of execution
#  - test
  - build
  - package
  - deploy

#test:
#  stage: test
#  tags:
#    - deployment
#  image: maven:3.8.5-openjdk-17
#  script:
#    - pwd
#    - echo $BACKEND_DIR
#    - cd $BACKEND_DIR
#    - mvn -version
#    - mvn clean install -Dspring.profiles.active=prod
#  only:
#    - ci-cd-backend

build:
  stage: build
  tags:
    - deployment
  image: maven:3.8.5-openjdk-17
  script:
    - pwd
    - cd $BACKEND_DIR
    - mvn clean package -Dspring.profiles.active=prod
  artifacts:
    paths:
      - $BACKEND_DIR/target/*.jar
  only:
    - ci-cd-backend

package:
  image: docker:latest
  variables:
    # these values may need to be different if using TLS, k8s, etc.
    # You can alternatively set defaults in your runner config
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  services:
    - docker:dind
  stage: package
  tags:
    - deployment
  script:
    - pwd
    - ls -la ServerSide/TourAssist/target/
    - docker build -t docker.io/patelraj22777/test:$CI_COMMIT_SHORT_SHA $BACKEND_DIR/target/
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io
    - docker push docker.io/patelraj22777/test:$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull docker.io/patelraj22777/test:$CI_COMMIT_SHORT_SHA"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f my-app || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 8073:8080 --name my-app docker.io/patelraj22777/test:$CI_COMMIT_SHORT_SHA"
  environment:
    name: production
    url: http://172.17.0.148:8073
  only:
    - ci-cd-backend
