spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: testuser
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /custom-h2-console

application:
  security:
    jwt:
      secret-key: idr7T5JBeraYvPQWcrtj5RLxdak43JJlUd0OTghkzUc=
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

storage:
  cloud-name: dnm5uzsbl
  access-key: 854872313461948
  secret-key: e2gLOFlmFp_S9OVkzkL6nzNoWrQ

